### ISSUE TITLE
Como alterar o plugin

### ISSUE THREAD

**Issue by dabraga** [andretimm/vscode-fluig#3]
André , 

Poderia passar o como faço configurar no vs Code ,e testar as alterações feitas

**Comment by andretimm** [comment]
Ola,

Ainda não gerei uma nova versão do plugin com as alterações por falta de tempo.
Mas para testar ele em modo desenvolvedor você vai precisaro do yarn na versão 1.17.3 (que foi a que utilizei, caso queria testar com outra fique a vontade).

Após clonar o projeto, execute o comando ``yarn install`` para baixar as dependências. Para rodar o projeto, abra o projeto no vs code e aperte ``F5``, e irá rodar o projeto em modo desenvolverem outra janela.

Qualquer duvida estou a disposição.
