### ISSUE TITLE
Não consigo trazer meus arquivos

### ISSUE THREAD

**Issue by deisecouto** [andretimm/vscode-fluig#7]
Bom dia, 

consegui conectar no meu servidor, porém não traz nenhum pasta, poderia me ajudar?

![image](https://user-images.githubusercontent.com/49957030/98378046-48f72500-2024-11eb-8259-25e07526d8a9.png)

**Comment by msmosso** [comment]
Bom dia @deisecouto,

A extensão não traz os arquivos do servidor, nem o Fluig Studio faz isso. Você deve ter uma pasta com os arquivos e utilizar a extensão para enviá-los ao servidor. Lembrando que apenas as seguintes funcionalidades foram implementadas até o momento:

![image](https://user-images.githubusercontent.com/530015/98378489-dcc8f100-2024-11eb-807f-900c1de2c041.png)

**Comment by andretimm** [comment]
Exatamente isso.

Podemos tentar pensar numa maneira do plugin ja trazer tudo, assim que a conexão for realizada. Mas isso ficaria pra um futuro.
